### ISSUE TITLE
Set background color

### ISSUE THREAD

**Issue by falahati1987** [dchest/captcha#21]
Hi everybody,

I was wondering how one can change background color to something other than transparent.

**Comment by dchest** [comment]
There's no such setting. But since it's transparent, why not set the background color of a div under the image in CSS?

**Comment by falahati1987** [comment]
Goo idea,
Is there any restrictions on the range of foreground colors? I want to make sure about generating discriminating captcha  from its background?

**Comment by falahati1987** [comment]
I feel better if you limit the range or use single color.

**Comment by dchest** [comment]
I should do this in the next version, yes. For now, feel free to fork it and change the lines that I linked to above.

**Comment by falahati1987** [comment]
Thank you so much
