### ISSUE TITLE
captcha: id not found

### ISSUE THREAD

**Issue by yuanhao2015** [dchest/captcha#25]
captcha: id not found，but I have entered the correct ID，why？

**Comment by Bingordinary** [comment]
There is a bug in the process of getting data from the data store. I encountered  the same error while verifying captcha in String and I have tried to fix it but I give up in the end.
Maybe you can try to fix it,good luck.

**Comment by dchest** [comment]
Could it be expired? (default expiration time is 10 minutes)

**Comment by kaisawind** [comment]
there is no bug here, i think.
the id will be removed from store, If you have verified  it.

https://github.com/dchest/captcha/blob/6a29415a8364ec2971fdc62d9e415ed53fc20410/captcha.go#L134-L143
