### ISSUE TITLE
provide `New() (id , solution string)`

### ISSUE THREAD

**Issue by mh-cbon** [dchest/captcha#28]
Hi,

I am in a case where i want the api to give both id and solution when invoking its service.

Some explanations, I need that while using captcha within a JSON API. Currently i only send back an id, with these new api i will be able to cipher the solution using a private key, and signing the message, which i will answer along the id. Using that i can validate any captcha issued by my api even though the service was restarted (i use no persistent db for captcha service), or, worst case, the api has totally changed because i only need to check the signed message, uncipher the solution and compare it with the JIT provided solution.

**Comment by dchest** [comment]
Your solution is insecure, because the attacker guess one captcha and then resend the same id and encrypted/signed solution to your server infinite number of times (or until it expires). Stateless captcha is not possible.

**Comment by mh-cbon** [comment]
I do fully agree that this is true for a "regular" clear net case, I can only ask you to consider i am not running against this network, so i can implement much more secure message exchanges. anyhow thank you for this interesting and good comment.

I am unclear about your decision concerning the addition of such func ?

**Comment by dchest** [comment]
See discussion here: https://github.com/dchest/captcha/pull/27

**Comment by mh-cbon** [comment]
cool thank you. sorry i have missed it, I title was unclear to me.
