### ISSUE TITLE
the spacing between the digits too small, even overlap. How to solve it?

### ISSUE THREAD

**Issue by wolking** [dchest/captcha#29]
captcha.NewLen(4)
captcha width:100
captcha height:34
result:
![captcha](https://user-images.githubusercontent.com/12195297/82651872-545dbc00-9c4f-11ea-8397-8ef97b27290f.png)
It's very illegible.

**Comment by dchest** [comment]
Yeah, unfortunately, only around the default length of 240x80 and larger is legible. For smaller images, I'd recommend either resizing them on the client (just specifying different width/height for the img tag) or resizing the `Image` you get in Go after it's generated.

**Comment by wolking** [comment]
> Yeah, unfortunately, only around the default length of 240x80 and larger is legible. For smaller images, I'd recommend either resizing them on the client (just specifying different width/height for the img tag) or resizing the `Image` you get in Go after it's generated.

Thanks for your advice.
