### ISSUE TITLE
how to use captcha in echo

### ISSUE THREAD

**Issue by madasatya6** [dchest/captcha#42]
I use the code as below but the url **localhost:port/captcha/** is not found :

```
e := echo.New()

e.GET("/captcha/", echo.WrapHandler(captcha.Server(captcha.StdWidth, captcha.StdHeight)))
```

please help me

**Comment by Kailian-Jacy** [comment]
Sometimes the routes may seems unpredictable for unfamiliar users.

Print the full routes registered by echo may helps. Check: https://echo.labstack.com/guide/routing/#list-routes
