### ISSUE TITLE
too difficult to recognize audio captcha

### ISSUE THREAD

**Issue by vapehacker** [dchest/captcha#44]
Hi, I found it really hard to recognize numbers (particularly, `0` `1` `5`) from background noise when trying audio captcha in Chinese, even with earphone. 

I'm a native listener, and I think most Chinese users would have the same feeling as me. As for me, passing the default audio captcha within 10 attempts is nearly impossible.

Could you please consider it, to replace the hard-to-recognize voices? What's more,  it is reasonable to allow developers to adjust the difficulty (for example, noise intensity). Thanks.

**Comment by dchest** [comment]
Thanks for letting me know! Please try changing the ranges for background sound level here:

https://github.com/dchest/captcha/blob/master/audio.go#L132

If you find a suitable level range that makes it easier to recognize numbers, please send a pull request.

**Comment by dchest** [comment]
Alternatively, if you can make better sounds for numbers, you can replace them here:

https://github.com/dchest/captcha/tree/master/capgensounds/zh

(see details in the README: https://github.com/dchest/captcha/blob/master/capgensounds/README.markdown)

I'd also appreciate a pull request for those.

**Comment by vapehacker** [comment]
Hello @dchest , I have updated part of sounds and changed the background sound level. Here is the PR: #45.

**Comment by dchest** [comment]
Great, thank you! Merged, and tagged the release.
