### ISSUE TITLE
Func VerifyString it works incorrectly

### ISSUE THREAD

**Issue by Nappy-Says** [dchest/captcha#46]
I was advised by a colleague to use this repository, as he was able to implement protection. 
When I started testing I ran into a problem -- verify and verifystring display false all the time.

code:
```
func main() {
	id := captcha.New()
	path_img, _ := os.Create("data.png")

	var w io.WriterTo
	digits := captcha.RandomDigits(6)
	w = captcha.NewImage(id, digits, 256, 128)
	w.WriteTo(path_img)

	var x string
	fmt.Scan(&x)
	fmt.Println(
		"result: ", captcha.VerifyString(id, x), 
		"\ngenerate digits:", digits, 
		"\nid:", id,
	)
}
```

result from console:
![image](https://user-images.githubusercontent.com/66124092/180422751-ce14511e-5b2a-45e4-b7db-ab1a8174905e.png)

**Comment by dchest** [comment]
On these lines:

```go
	digits := captcha.RandomDigits(6)
	w = captcha.NewImage(id, digits, 256, 128)
```

You just create new random digits. To generate an image with the actual digits that get stored in the global store when you call `captcha.New`, use:

```go
captcha.WriteImage(w, id, 256, 128)
```

Here's [how it's implemented](https://github.com/dchest/captcha/blob/master/captcha.go#L108).
